default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: Hatrung8888-
  host: db
  port: 3306

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

